# build_docs_inventory.py

"""Build the documentation inventory for SimpleChat user-facing surfaces."""

from __future__ import annotations

import argparse
import ast
import html
import re
import sys
from html.parser import HTMLParser
from pathlib import Path
from typing import Any

try:
    import yaml
except ImportError:
    yaml = None


REPO_ROOT = Path(__file__).resolve().parents[1]
APP_ROOT = REPO_ROOT / "application" / "single_app"
TEMPLATES_DIR = APP_ROOT / "templates"
PLUGINS_DIR = APP_ROOT / "semantic_kernel_plugins"
DEFAULT_OUTPUT_PATH = REPO_ROOT / "docs" / "_data" / "app_surface.yml"

GENERATED_HEADER = (
    "# Generated by scripts\\build_docs_inventory.py -- do not edit by hand.\n"
    "# Regenerate with: python scripts\\build_docs_inventory.py\n"
)

PLUGIN_INFRASTRUCTURE_FILES = {
    "__init__.py",
    "base_plugin.py",
    "logged_plugin_loader.py",
    "plugin_health_checker.py",
    "plugin_invocation_logger.py",
    "plugin_invocation_thoughts.py",
    "plugin_loader.py",
    "plugin_logging_examples.py",
    "sql_odbc_utils.py",
    "ui_test_plugin.py",
}

CHAT_CONTROL_ID_RE = re.compile(r"^[a-zA-Z0-9\-_]*(?:btn|button|toggle)[a-zA-Z0-9\-_]*$", re.IGNORECASE)
ENABLE_SETTING_RE = re.compile(r"enable_[a-z0-9_]+")
HTML_TAG_RE = re.compile(r"<[^>]+>")
JINJA_RE = re.compile(r"{[#%{].*?[#}%]}", re.DOTALL)


class TabParser(HTMLParser):
    """Extract Bootstrap tab controls from the admin settings template."""

    def __init__(self) -> None:
        super().__init__(convert_charrefs=True)
        self.tabs: list[dict[str, str]] = []
        self._active_indexes: list[int] = []

    def handle_starttag(self, tag: str, attrs: list[tuple[str, str | None]]) -> None:
        attr_map = {name: value or "" for name, value in attrs}
        if attr_map.get("data-bs-toggle") != "tab":
            return

        target = attr_map.get("data-bs-target") or attr_map.get("href") or ""
        if not target.startswith("#"):
            return

        self.tabs.append(
            {
                "id": target[1:],
                "tab_element_id": attr_map.get("id", ""),
                "_label_parts": [],
            }
        )
        self._active_indexes.append(len(self.tabs) - 1)

    def handle_data(self, data: str) -> None:
        for index in self._active_indexes:
            self.tabs[index]["_label_parts"].append(data)

    def handle_endtag(self, tag: str) -> None:
        if self._active_indexes and tag in {"a", "button"}:
            self._active_indexes.pop()

    def get_tabs(self) -> list[dict[str, str]]:
        tabs: list[dict[str, str]] = []
        for tab in self.tabs:
            label = normalize_label(" ".join(tab["_label_parts"]))
            tabs.append(
                {
                    "id": tab["id"],
                    "tab_element_id": tab["tab_element_id"],
                    "label": label,
                }
            )
        return sorted(tabs, key=lambda item: item["id"])


class ChatControlParser(HTMLParser):
    """Extract chat control elements and their labels from the chat template."""

    def __init__(self, source_lines: list[str]) -> None:
        super().__init__(convert_charrefs=True)
        self.source_lines = source_lines
        self.controls: list[dict[str, Any]] = []
        self._active_indexes: list[int] = []

    def handle_starttag(self, tag: str, attrs: list[tuple[str, str | None]]) -> None:
        attr_map = {name: value or "" for name, value in attrs}
        element_id = attr_map.get("id", "")
        if not CHAT_CONTROL_ID_RE.match(element_id):
            return

        line_number = self.getpos()[0]
        control = {
            "id": element_id,
            "_tag": tag,
            "_label_parts": [],
            "_line_number": line_number,
            "_title": attr_map.get("title", ""),
            "_aria_label": attr_map.get("aria-label", ""),
        }
        self.controls.append(control)
        self._active_indexes.append(len(self.controls) - 1)

    def handle_data(self, data: str) -> None:
        for index in self._active_indexes:
            self.controls[index]["_label_parts"].append(data)

    def handle_endtag(self, tag: str) -> None:
        for index in range(len(self._active_indexes) - 1, -1, -1):
            control = self.controls[self._active_indexes[index]]
            if control["_tag"] == tag:
                del self._active_indexes[index]
                break

    def get_controls(self) -> tuple[list[dict[str, Any]], list[dict[str, Any]]]:
        controls: list[dict[str, Any]] = []
        sub_elements: list[dict[str, Any]] = []
        for raw_control in self.controls:
            item: dict[str, Any] = {"id": raw_control["id"]}
            label = first_non_empty(
                raw_control["_title"],
                raw_control["_aria_label"],
                normalize_label(" ".join(raw_control["_label_parts"])),
            )
            if label:
                item["label"] = label

            enabled_by = self.get_nearby_settings(raw_control["_line_number"])
            if enabled_by:
                item["enabled_by"] = enabled_by

            if is_chat_control_sub_element(raw_control["id"]):
                sub_elements.append(item)
            else:
                controls.append(item)

        return (
            sorted(controls, key=lambda item: item["id"]),
            sorted(sub_elements, key=lambda item: item["id"]),
        )

    def get_nearby_settings(self, line_number: int) -> list[str]:
        start = max(0, line_number - 6)
        end = min(len(self.source_lines), line_number + 5)
        nearby_source = "\n".join(self.source_lines[start:end])
        return sorted(set(ENABLE_SETTING_RE.findall(nearby_source)))


def first_non_empty(*values: str) -> str:
    """Return the first normalized non-empty string."""
    for value in values:
        normalized = normalize_label(value)
        if normalized:
            return normalized
    return ""


def normalize_label(value: str) -> str:
    """Collapse markup, Jinja fragments, and whitespace into a readable label."""
    without_jinja = JINJA_RE.sub(" ", value)
    without_tags = HTML_TAG_RE.sub(" ", without_jinja)
    unescaped = html.unescape(without_tags)
    return re.sub(r"\s+", " ", unescaped).strip()


def is_chat_control_sub_element(element_id: str) -> bool:
    """Return True for child labels/spinners that support a parent control."""
    return element_id.endswith(("-label", "-spinner"))


def kebab_case(value: str) -> str:
    """Convert snake-style file stems to kebab-case slugs."""
    return value.replace("_", "-")


def read_text(path: Path) -> str:
    """Read a source file as UTF-8."""
    return path.read_text(encoding="utf-8")


def extract_version() -> str:
    """Read the application version from config.py without importing application code."""
    config_text = read_text(APP_ROOT / "config.py")
    match = re.search(r'^\s*VERSION\s*=\s*["\']([^"\']+)["\']', config_text, re.MULTILINE)
    if not match:
        raise ValueError("Unable to find VERSION in application\\single_app\\config.py.")
    return match.group(1)


def extract_capabilities() -> list[dict[str, Any]]:
    """Extract enable_* settings from the default settings dictionary."""
    settings_text = read_text(APP_ROOT / "functions_settings.py")
    capabilities_by_key: dict[str, dict[str, Any]] = {}
    pattern = re.compile(r"^\s*'(?P<key>enable_[a-z0-9_]+)'\s*:\s*(?P<default>True|False|true|false)?", re.MULTILINE)
    for match in pattern.finditer(settings_text):
        key = match.group("key")
        if key in capabilities_by_key:
            continue

        item: dict[str, Any] = {"key": key}
        default_value = match.group("default")
        if default_value is not None:
            item["default"] = default_value.lower() == "true"
        capabilities_by_key[key] = item
    return sorted(capabilities_by_key.values(), key=lambda item: item["key"])


def extract_admin_tabs() -> list[dict[str, str]]:
    """Extract admin settings Bootstrap tabs."""
    parser = TabParser()
    parser.feed(read_text(TEMPLATES_DIR / "admin_settings.html"))
    return parser.get_tabs()


def extract_primary_class(path: Path) -> tuple[str | None, str | None]:
    """Return the primary user-facing plugin class and its docstring first line."""
    tree = ast.parse(read_text(path), filename=str(path))
    classes = [node for node in ast.walk(tree) if isinstance(node, ast.ClassDef) and not node.name.startswith("_")]
    plugin_classes = [node for node in classes if node.name.endswith("Plugin")]
    selected = plugin_classes[0] if plugin_classes else (classes[0] if classes else None)
    if selected is None:
        return None, None

    docstring = ast.get_docstring(selected) or ""
    summary = docstring.strip().splitlines()[0].strip() if docstring.strip() else None
    return selected.name, summary


def extract_actions() -> list[dict[str, Any]]:
    """Extract Semantic Kernel plugin action types."""
    actions: list[dict[str, Any]] = []
    for path in sorted(PLUGINS_DIR.glob("*.py"), key=lambda item: item.name):
        if path.name in PLUGIN_INFRASTRUCTURE_FILES or path.name.endswith("_plugin_factory.py"):
            continue

        stem = path.stem
        base_name = stem.removesuffix("_plugin")
        class_name, summary = extract_primary_class(path)
        item: dict[str, Any] = {
            "slug": kebab_case(base_name),
            "module": path.name,
        }
        if class_name:
            item["class_name"] = class_name
        if summary:
            item["summary"] = summary
        actions.append(item)

    return sorted(actions, key=lambda item: item["slug"])


def extract_chat_controls() -> tuple[list[dict[str, Any]], list[dict[str, Any]]]:
    """Extract interactive chat controls and supporting sub-elements."""
    chat_text = read_text(TEMPLATES_DIR / "chats.html")
    parser = ChatControlParser(chat_text.splitlines())
    parser.feed(chat_text)
    return parser.get_controls()


def get_ast_name(node: ast.AST | None) -> str | None:
    """Return a dotted name for supported AST nodes."""
    if isinstance(node, ast.Name):
        return node.id
    if isinstance(node, ast.Attribute):
        parent = get_ast_name(node.value)
        return f"{parent}.{node.attr}" if parent else node.attr
    if isinstance(node, ast.Call):
        return get_ast_name(node.func)
    return None


def is_route_decorator(node: ast.AST) -> bool:
    """Return True when a decorator is a Flask or Blueprint route decorator."""
    return isinstance(node, ast.Call) and bool(get_ast_name(node.func) and get_ast_name(node.func).endswith(".route"))


def get_route_urls(node: ast.FunctionDef | ast.AsyncFunctionDef) -> list[str]:
    """Extract static route URLs from a route function's decorators."""
    urls: list[str] = []
    for decorator in node.decorator_list:
        if not is_route_decorator(decorator):
            continue
        if decorator.args and isinstance(decorator.args[0], ast.Constant) and isinstance(decorator.args[0].value, str):
            urls.append(decorator.args[0].value)
    return sorted(set(urls))


def iter_rendered_templates(node: ast.FunctionDef | ast.AsyncFunctionDef) -> set[str]:
    """Return static template names rendered inside a function."""
    templates: set[str] = set()
    for child in ast.walk(node):
        if not isinstance(child, ast.Call) or get_ast_name(child.func) != "render_template":
            continue
        if child.args and isinstance(child.args[0], ast.Constant) and isinstance(child.args[0].value, str):
            templates.add(child.args[0].value)
    return templates


def extract_template_routes() -> dict[str, list[str]]:
    """Map rendered templates to route URLs by statically inspecting route modules."""
    route_files = sorted(APP_ROOT.glob("route_*.py"), key=lambda item: item.name)
    app_file = APP_ROOT / "app.py"
    if app_file.exists():
        route_files.append(app_file)

    template_routes: dict[str, set[str]] = {}
    for route_file in route_files:
        tree = ast.parse(read_text(route_file), filename=str(route_file))
        for node in ast.walk(tree):
            if not isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
                continue
            route_urls = get_route_urls(node)
            if not route_urls:
                continue
            for template in iter_rendered_templates(node):
                template_routes.setdefault(template, set()).update(route_urls)

    return {template: sorted(urls) for template, urls in template_routes.items()}


def extract_app_pages() -> list[dict[str, Any]]:
    """Extract top-level user-facing template pages."""
    template_routes = extract_template_routes()
    pages: list[dict[str, Any]] = []
    for path in sorted(TEMPLATES_DIR.glob("*.html"), key=lambda item: item.name):
        if path.name.startswith("_") or path.name == "base.html":
            continue

        route_urls = template_routes.get(path.name, [])
        item: dict[str, Any] = {
            "template": path.name,
            "slug": kebab_case(path.stem),
        }
        if route_urls:
            item["route_url"] = route_urls[0]
            if len(route_urls) > 1:
                item["route_urls"] = route_urls
        pages.append(item)

    return sorted(pages, key=lambda item: item["template"])


def extract_feature_surfaces() -> list[dict[str, str]]:
    """Extract modal and partial feature surfaces."""
    surfaces: list[dict[str, str]] = []
    for path in sorted(TEMPLATES_DIR.glob("_*.html"), key=lambda item: item.name):
        surfaces.append(
            {
                "template": path.name,
                "slug": kebab_case(path.stem.removeprefix("_")),
            }
        )
    return sorted(surfaces, key=lambda item: item["template"])


def build_inventory() -> dict[str, Any]:
    """Build the complete application surface inventory."""
    chat_controls, sub_elements = extract_chat_controls()
    inventory = {
        "generated_from_version": extract_version(),
        "capabilities": extract_capabilities(),
        "admin_tabs": extract_admin_tabs(),
        "actions": extract_actions(),
        "chat_controls": chat_controls,
        "sub_elements": sub_elements,
        "app_pages": extract_app_pages(),
        "feature_surfaces": extract_feature_surfaces(),
    }
    inventory["counts"] = {
        "capabilities": len(inventory["capabilities"]),
        "admin_tabs": len(inventory["admin_tabs"]),
        "actions": len(inventory["actions"]),
        "chat_controls": len(inventory["chat_controls"]),
        "sub_elements": len(inventory["sub_elements"]),
        "app_pages": len(inventory["app_pages"]),
        "feature_surfaces": len(inventory["feature_surfaces"]),
    }
    return {
        "generated_from_version": inventory["generated_from_version"],
        "counts": inventory["counts"],
        "capabilities": inventory["capabilities"],
        "admin_tabs": inventory["admin_tabs"],
        "actions": inventory["actions"],
        "chat_controls": inventory["chat_controls"],
        "sub_elements": inventory["sub_elements"],
        "app_pages": inventory["app_pages"],
        "feature_surfaces": inventory["feature_surfaces"],
    }


def dump_yaml(data: dict[str, Any]) -> str:
    """Serialize inventory data to deterministic YAML."""
    version = data["generated_from_version"]
    body_data = dict(data)
    del body_data["generated_from_version"]
    if yaml is not None:
        body = yaml.safe_dump(
            body_data,
            sort_keys=False,
            allow_unicode=True,
            default_flow_style=False,
            width=120,
        )
    else:
        body = dump_yaml_manually(body_data)
    return f'{GENERATED_HEADER}generated_from_version: "{version}"\n{body}'


def dump_yaml_manually(data: Any, indent: int = 0) -> str:
    """Fallback deterministic YAML dumper for this inventory's simple data types."""
    lines: list[str] = []
    prefix = " " * indent
    if isinstance(data, dict):
        for key, value in data.items():
            if isinstance(value, (dict, list)):
                lines.append(f"{prefix}{key}:")
                lines.append(dump_yaml_manually(value, indent + 2).rstrip("\n"))
            else:
                lines.append(f"{prefix}{key}: {format_yaml_scalar(value)}")
    elif isinstance(data, list):
        for item in data:
            if isinstance(item, dict):
                lines.append(f"{prefix}- {next(iter(item))}: {format_yaml_scalar(next(iter(item.values())))}")
                for key, value in list(item.items())[1:]:
                    if isinstance(value, (dict, list)):
                        lines.append(f"{prefix}  {key}:")
                        lines.append(dump_yaml_manually(value, indent + 4).rstrip("\n"))
                    else:
                        lines.append(f"{prefix}  {key}: {format_yaml_scalar(value)}")
            else:
                lines.append(f"{prefix}- {format_yaml_scalar(item)}")
    return "\n".join(lines) + "\n"


def format_yaml_scalar(value: Any) -> str:
    """Format a scalar for the manual YAML fallback."""
    if isinstance(value, bool):
        return "true" if value else "false"
    if value is None:
        return "null"
    if isinstance(value, (int, float)):
        return str(value)
    escaped = str(value).replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def print_counts(inventory: dict[str, Any]) -> None:
    """Print a concise extraction summary."""
    counts = inventory["counts"]
    summary = ", ".join(f"{key}: {value}" for key, value in counts.items())
    print(f"Wrote docs inventory ({summary}).")


def parse_args() -> argparse.Namespace:
    """Parse command-line arguments."""
    parser = argparse.ArgumentParser(description="Build the SimpleChat documentation surface inventory.")
    parser.add_argument("--check", action="store_true", help="Exit non-zero if the inventory file is out of date.")
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT_PATH, help="Destination YAML path.")
    return parser.parse_args()


def main() -> int:
    """Run the inventory builder."""
    args = parse_args()
    output_path = args.output
    if not output_path.is_absolute():
        output_path = REPO_ROOT / output_path

    inventory = build_inventory()
    rendered = dump_yaml(inventory)

    if args.check:
        existing = output_path.read_text(encoding="utf-8") if output_path.exists() else ""
        if existing != rendered:
            print(f"Inventory is out of date: {output_path}", file=sys.stderr)
            return 1
        print(f"Inventory is in sync: {output_path}")
        return 0

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(rendered, encoding="utf-8", newline="\n")
    print_counts(inventory)
    return 0


if __name__ == "__main__":
    sys.exit(main())
