#!/usr/bin/env python3
"""
Functional test for documentation coverage of the application surface.
Version: 0.250.230
Implemented in: 0.250.230

This test ensures that every user-facing capability of SimpleChat has
documentation on the docs site. It is the mechanism that keeps documentation
current as pull requests land: adding a new settings toggle, admin settings
tab, action plugin, or chat control without documenting it fails this test.

The application surface is captured in docs/_data/app_surface.yml, which is
generated by scripts/build_docs_inventory.py. This test also verifies that
inventory is still in sync with the application, so a stale inventory cannot be
used to hide missing documentation.
"""

import io
import os
import re
import subprocess
import sys
from pathlib import Path

sys.path.append(os.path.dirname(os.path.abspath(__file__)))

import yaml

from test_support.versioning import assert_app_version_at_least

REPO_ROOT = Path(__file__).resolve().parents[1]
DOCS_ROOT = REPO_ROOT / "docs"
APP_SURFACE = DOCS_ROOT / "_data" / "app_surface.yml"
INVENTORY_SCRIPT = REPO_ROOT / "scripts" / "build_docs_inventory.py"

# Documentation folders that count as coverage. Engineering notes under
# docs/explanation/features and docs/explanation/fixes are deliberately excluded
# because they are internal change records, not user documentation, and they are
# excluded from the published site.
DOC_GLOBS = (
    "admin/*.md",
    "guides/*.md",
    "guides/**/*.md",
    "reference/*.md",
    "reference/**/*.md",
    "how-to/*.md",
    "how-to/**/*.md",
    "tutorials/*.md",
    "features/*.md",
    "*.md",
)

# Capability toggles that are internal implementation or telemetry switches
# rather than user-facing features. Each entry must state why it is exempt.
# Keep this list short and justified; it is the only escape hatch in this test.
CAPABILITY_EXEMPTIONS = {
    "enable_analysis_deliverable_contract_telemetry": "Internal telemetry switch for deliverable contract diagnostics.",
    "enable_tabular_parity_contract_telemetry": "Internal telemetry switch for tabular parity diagnostics.",
    "enable_mixed_source_development_telemetry": "Internal development telemetry switch.",
    "enable_dai_debug": "Internal Document Intelligence debug switch.",
    "enable_tabular_generation_balanced_batches": "Internal tabular batching tuning flag.",
    "enable_tabular_completion_driven_checkpointing": "Internal tabular checkpointing tuning flag.",
    "enable_tabular_independent_batch_retries": "Internal tabular retry tuning flag.",
    "enable_tabular_rolling_worker_pool": "Internal tabular worker pool tuning flag.",
    "enable_tabular_analyze_durable_preflight": "Internal tabular preflight tuning flag.",
    "enable_tabular_search_shared_preflight": "Internal tabular preflight tuning flag.",
    "enable_tabular_compact_response_protocol": "Internal tabular protocol tuning flag.",
    "enable_tabular_durable_run_confirmation": "Internal tabular durability tuning flag.",
    "enable_tabular_generation_plan": "Internal tabular planning tuning flag.",
    "enable_tabular_hierarchical_analysis": "Internal tabular planning tuning flag.",
    "enable_tabular_mixed_deferred_composition_planning": "Internal tabular planning tuning flag.",
    "enable_tabular_multifile_execution_unit_planning": "Internal tabular planning tuning flag.",
    "enable_document_access_index_cache": "Internal Cosmos access-index rollout flag.",
    "enable_document_access_index_container": "Internal Cosmos access-index rollout flag.",
    "enable_document_access_index_reads": "Internal Cosmos access-index rollout flag.",
    "enable_document_access_index_shadow_validation": "Internal Cosmos access-index rollout flag.",
    "enable_document_access_index_write_through": "Internal Cosmos access-index rollout flag.",
    "enable_startup_document_access_index_backfill": "Internal Cosmos access-index rollout flag.",
    "enable_mixed_source_manifest": "Internal mixed-source rollout flag.",
    "enable_mixed_source_relevance_candidates": "Internal mixed-source rollout flag.",
    "enable_startup_app_maintenance": "Internal startup maintenance switch.",
    "enable_default_embedding_model_plugin": "Internal plugin registration default.",
}


def load_inventory():
    """Load the generated application surface inventory."""
    if not APP_SURFACE.exists():
        raise AssertionError(
            f"Missing {APP_SURFACE.relative_to(REPO_ROOT)}. "
            "Run: python scripts/build_docs_inventory.py"
        )
    return yaml.safe_load(io.open(APP_SURFACE, encoding="utf-8"))


def load_docs_corpus():
    """Concatenate the text of every published documentation page."""
    seen = set()
    chunks = []

    for pattern in DOC_GLOBS:
        for path in DOCS_ROOT.glob(pattern):
            if not path.is_file() or path in seen:
                continue
            parts = set(path.relative_to(DOCS_ROOT).parts)
            if "_site" in parts or "fixes" in parts:
                continue
            seen.add(path)
            chunks.append(io.open(path, encoding="utf-8", errors="ignore").read())

    if not chunks:
        raise AssertionError("No documentation pages were found to scan.")

    return "\n".join(chunks)


def report_missing(label, missing, total, remediation):
    """Format a coverage failure message."""
    return (
        f"{label}: {len(missing)} of {total} are undocumented.\n"
        f"  Missing: {', '.join(sorted(missing)[:25])}"
        f"{' ...' if len(missing) > 25 else ''}\n"
        f"  {remediation}"
    )


def test_inventory_is_in_sync():
    """The generated inventory must match the current application."""
    print("Checking docs/_data/app_surface.yml is in sync with the application...")

    if not INVENTORY_SCRIPT.exists():
        print(f"  Skipped: {INVENTORY_SCRIPT.relative_to(REPO_ROOT)} not found.")
        return True

    result = subprocess.run(
        [sys.executable, str(INVENTORY_SCRIPT), "--check"],
        cwd=str(REPO_ROOT),
        capture_output=True,
        text=True,
    )

    if result.returncode != 0:
        print("Inventory is stale. Regenerate it with:")
        print("  python scripts/build_docs_inventory.py")
        print(result.stdout.strip())
        print(result.stderr.strip())
        return False

    print("  Inventory is current.")
    return True


def test_admin_tab_coverage():
    """Every admin settings tab must have a documentation page."""
    print("Checking admin settings tab documentation coverage...")

    inventory = load_inventory()
    tabs = [tab["id"] for tab in inventory.get("admin_tabs", [])]
    missing = [tab for tab in tabs if not (DOCS_ROOT / "admin" / f"{tab}.md").exists()]

    if missing:
        print(report_missing(
            "Admin settings tabs", missing, len(tabs),
            "Add a page at docs/admin/<tab-id>.md for each missing tab.",
        ))
        return False

    print(f"  All {len(tabs)} admin settings tabs are documented.")
    return True


def test_action_coverage():
    """Every action plugin must be documented."""
    print("Checking action documentation coverage...")

    inventory = load_inventory()
    actions = [action["slug"] for action in inventory.get("actions", [])]
    corpus = load_docs_corpus()

    missing = []
    for slug in actions:
        page = DOCS_ROOT / "reference" / "actions" / f"{slug}.md"
        if page.exists():
            continue
        if slug in corpus:
            continue
        missing.append(slug)

    if missing:
        print(report_missing(
            "Actions", missing, len(actions),
            "Add a page at docs/reference/actions/<slug>.md for each missing action.",
        ))
        return False

    print(f"  All {len(actions)} actions are documented.")
    return True


def test_chat_control_coverage():
    """Every chat control must appear in the chat interface reference."""
    print("Checking chat control documentation coverage...")

    inventory = load_inventory()
    controls = [control["id"] for control in inventory.get("chat_controls", [])]
    corpus = load_docs_corpus()

    missing = [control for control in controls if control not in corpus]

    if missing:
        print(report_missing(
            "Chat controls", missing, len(controls),
            "Document each control in docs/reference/chat-controls.md.",
        ))
        return False

    print(f"  All {len(controls)} chat controls are documented.")
    return True


def test_capability_coverage():
    """Every user-facing capability toggle must be documented."""
    print("Checking capability toggle documentation coverage...")

    inventory = load_inventory()
    capabilities = [capability["key"] for capability in inventory.get("capabilities", [])]
    corpus = load_docs_corpus()

    missing = [
        key for key in capabilities
        if key not in corpus and key not in CAPABILITY_EXEMPTIONS
    ]

    if missing:
        print(report_missing(
            "Capability toggles", missing, len(capabilities),
            "Document each toggle on the relevant docs/admin/<tab>.md page, or add a "
            "justified entry to CAPABILITY_EXEMPTIONS in this test if it is an "
            "internal-only flag.",
        ))
        return False

    documented = len(capabilities) - len(CAPABILITY_EXEMPTIONS)
    print(f"  {documented} user-facing capability toggles are documented "
          f"({len(CAPABILITY_EXEMPTIONS)} internal flags exempt).")
    return True


def test_exemptions_are_still_real():
    """Exempted toggles must still exist, so the list cannot rot."""
    print("Checking capability exemption list has no stale entries...")

    inventory = load_inventory()
    capabilities = {capability["key"] for capability in inventory.get("capabilities", [])}
    stale = sorted(key for key in CAPABILITY_EXEMPTIONS if key not in capabilities)

    if stale:
        print(f"  These exemptions reference toggles that no longer exist: {', '.join(stale)}")
        print("  Remove them from CAPABILITY_EXEMPTIONS in this test.")
        return False

    print(f"  All {len(CAPABILITY_EXEMPTIONS)} exemptions reference real toggles.")
    return True


if __name__ == "__main__":
    assert_app_version_at_least("0.250.230")

    tests = [
        test_inventory_is_in_sync,
        test_admin_tab_coverage,
        test_action_coverage,
        test_chat_control_coverage,
        test_capability_coverage,
        test_exemptions_are_still_real,
    ]

    results = []
    for test in tests:
        print(f"\nRunning {test.__name__}...")
        try:
            results.append(test())
        except Exception as error:  # noqa: BLE001 - report and continue
            print(f"Test raised an exception: {error}")
            import traceback
            traceback.print_exc()
            results.append(False)

    print(f"\nResults: {sum(1 for r in results if r)}/{len(results)} checks passed")
    sys.exit(0 if all(results) else 1)
